version: "3.9"
services:
  app:
    build:
      context: .docker
      dockerfile: app.Dockerfile
    volumes:
      # Workspace
      - ./app:/app
      # WSLg
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
    environment:
      # WSLg
      - DISPLAY=$DISPLAY
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - PULSE_SERVER=$PULSE_SERVER
      # USB
      - /dev/bus/usb:/dev/bus/usb:ro
    privileged: true
